### ISSUE TITLE
IE浏览器兼容性问题

### ISSUE THREAD

**Issue by renxionghui** [zhangzhengyi12/vue-scrollbars#1]
错误提示:SCRIPT438: 对象不支持“debounceHide”属性或方法

**Comment by renxionghui** [comment]
设置了高度之后没有再出现:对象不支持“debounceHide”属性或方法的问题,可是Y轴滚动条的高度为0px,鼠标滚轮可以滚动,(IE浏览器滚动条高度为0,谷歌正常)

**Comment by zhangzhengyi12** [comment]
请问是Edge吗，电脑上目前没有IE .我会进行关注和解决的，感谢你的issues

**Comment by zhangzhengyi12** [comment]
我在win10 1809上的edge和IE11上没有发现该问题 请提供具体的IE版本
