### ISSUE TITLE
滚动条中的滑块高度为0,不知道为什么

### ISSUE THREAD

**Issue by Mrzhaozhang** [zhangzhengyi12/vue-scrollbars#3]

**Comment by coolicer** [comment]
@Mrzhaozhang 我也遇到，你是怎么解决的

**Comment by Mrzhaozhang** [comment]
http://github.serafin.io/vuebar/&nbsp; &nbsp;用这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 上午10:25
收件人: ***@***.***&gt;; 
抄送: "(12G5J11) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangzhengyi12/vue-scrollbars] 滚动条中的滑块高度为0,不知道为什么 (#3)





 
@Mrzhaozhang 我也遇到，你是怎么解决的

**Comment by coolicer** [comment]
@Mrzhaozhang 我换了el-scrollbar + vue-infinite-scroll。然后出现了一样的问题，我才发现会不会是我用了nuxtjs的原故。后面证实了这个猜想。
